server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  application:
    name: PERSON-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5050/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost


